services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Steve@123
      MYSQL_DATABASE: Sew_StyleData
      MYSQL_USER: Steve
      MYSQL_PASSWORD: Steve@123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  springbootapp:
    image: otizaaa/sewstyles-backend:latest
    container_name: Sew-Styles-app
    ports:
      - "8080:5000"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Sew_StyleData?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: Steve
      SPRING_DATASOURCE_PASSWORD: Steve@123
      SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect

volumes:
  mysql-data:



