version: '3.8'

services:
  # MySQL Database Service
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword123
      MYSQL_DATABASE: sew_style_data
      MYSQL_USER: user
      MYSQL_PASSWORD: userPassword123
    ports:
      - "4000:3306"  # Expose port 3306 to allow connection from MySQL Workbench
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data between container restarts
    networks:
      - mysql_network

  # Spring Boot Application Service
  sew_style_backend:
    image: ameda/sew_style  # The image name you've built and pushed
    container_name: sew_style_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/sew_style_data  # Connect to MySQL service
      SPRING_DATASOURCE_USERNAME: root  # Use the username from the MySQL service
      SPRING_DATASOURCE_PASSWORD: rootPassword123  # Password for the non-root MySQL user
      SPRING_JPA_HIBERNATE_DDL_AUTO: update  # Automatically manage the schema (optional)
    ports:
      - "8080:8080"  # Expose port 8080 for accessing the Spring Boot app
    depends_on:
      - mysql_db  # Ensure MySQL starts before the Spring Boot application
    networks:
      - mysql_network

volumes:
  mysql_data:
    driver: local

networks:
  mysql_network:
    driver: bridge
