version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword123
      MYSQL_DATABASE: sew_style_data
      MYSQL_USER: Steve
      MYSQL_PASSWORD: Steve@123
    ports:
      - "4000:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  sew_style_backend:
    image: otizaaa/sew_style # Default to your pushed image
    container_name: sew_style_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/sew_style_data?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: Steve
      SPRING_DATASOURCE_PASSWORD: Steve@123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      JWT_SECRET: your-very-long-secret-key-here  # Change later if needed
      JWT_EXPIRATION: 86400000
    ports:
      - "8000:8000"
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - mysql_network

volumes:
  mysql_data:
    driver: local

networks:
  mysql_network:
    driver: bridge
